services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: interview
    ports:
      - "8084:8084"
    environment:
      BOT_USERNAME: ${BOT_USERNAME}
      TOKEN_BOT: ${TOKEN_BOT}
    restart: always