services:
  app:
    image: interview-results-bot-app:latest
    container_name: interview-bot
    restart: always
    ports:
      - "8084:8084"
    environment:
      BOT_USERNAME: ${BOT_USERNAME}
      TOKEN_BOT: ${TOKEN_BOT}
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge