app:
  bot:
    token: ${TOKEN_BOT}
    username: ${BOT_USERNAME}

spring:
  output:
    ansi:
      enabled: always

  config:
    import: optional:file:.env[.properties]

logging:
  config: classpath:logback-spring.xml